### ISSUE TITLE
Link/Unlink 

### ISSUE THREAD

**Issue by KhaozFrost** [Eufranio/MBDiscordLink#1]
ok.. pressed enter way to quickly um. so the sync role thing, it will add them to the role when they are in the right group but it wont remove their role when they dont have the right perm.  So lets say i made 2 teams;

discord.solar
discord.lunar

well in-game i have an option to switch between the two.. it removes them from 1 group and adds them to another. well discord link wont actually remove them from the group they dont have perms to and add them to the correct one or vise versa which i need it to

**Comment by Eufranio** [comment]
?

**Comment by KhaozFrost** [comment]
sorry. :/ i pressed enter way to fast. updated the OP

**Comment by Eufranio** [comment]
I see. It is expected that you gain a role from a perm, not the other way around, but I'm going to add this anyway soon. Thanks for the suggestion.

**Comment by KhaozFrost** [comment]
appreciate this. I'd love for it to be able to update players roles when they lose perms. really do love the plugin appreciate this linking thing but most def would be beneficial to be able to keep players roles updated like this. especially with a rankup like system even like my dex ranks

**Comment by Eufranio** [comment]
Try using the latest version, I added that as a feature.
