### ISSUE TITLE
Unable to link using Discord bot

### ISSUE THREAD

**Issue by willbattel** [Eufranio/MBDiscordLink#10]
My MagiBridge connection to my Discord server is working. That is, game chat is being sent to the Discord channel, and Discord chat is being sent to the game chat. The Discord bot that manages the channel (i.e., setting the Discord channel topic, sending messages such as "player joined the game", etc...) is otherwise working.

However, I am unable to get the Discord bot to complete the link. With `/link` in the game, I am given the 4 digit code. When I send that code to the Discord bot, nothing happens. There is no feedback whatsoever, so I cannot determine where the issue is. The linked user role is not added to my Discord user, and there is no other indication of success or failure to link. I have given the Discord bot every permission to make sure it is

I am using the default config on a SpongeForge 1.12 server, with MBDiscordLink 1.6 and MagiBridge 2.7.

Perhaps I need a different version of MagiBridge for MBDiscordLink 1.6? Or should I try MagiBridge 2.6.2 with MBDiscordLink 1.5?

Any ideas? Thanks.

**Comment by se7enek** [comment]
@Eufranio 

im having same issue.
Using MBDiscordLink 1.6 with MagiBridge 2.7

Console giving me no output, beside the fact i executed command.
Role `linked-users-role=minecraft` exists in my discord server and Bot having all permissions.
`roles-to-sync` setting also has correct RoleID set in config.

**Comment by se7enek** [comment]
MagiBridge 2.6.2 with MBDiscordLink 1.5 is working fine on SAME configs.

**Comment by willbattel** [comment]
@se7enek did reverting to that version result in any undesired changes, or did everything else work the same as the latest version?

**Comment by se7enek** [comment]
Sorry was kinda away. Actually, didnt notice any differences between latest working "combo" and the latest release. For my needs, MagiBridge is doing fine if its about discord<>minecraft link. + Registration of members by using MBDiscordLink. Usually trying to use latest versions but if these dont work (just MBDiscordLink was not working), then i need to find other solutions (which was downgrading).

**Comment by YuRaNnNzZZ** [comment]
Same here. Nothing happens after sending the 4-digit code to bot.
MB 2.8.1, MBDiscordLink 1.6, SpongeForge 2838-7.1.7-RC3928

Edit: downgrading to MagiBridge 2.6.2 and MBDiscordLink 1.5 resolves the issue.

**Comment by JadedMagic1** [comment]
So I had been running on MagiBridge 2.8.2, downgraded to MagiBridge 2.6.2 and MBDiscordLink 1.5. Link works like a charm, Minecraft -> Discord is good, but getting 0 data from Discord -> Minecraft. Did a fresh look thru the configs, all IDs are proper, just cant get messages to show up in Minecraft like I had in MagiBridge 2.8.2

**Comment by Eufranio** [comment]
MBDiscordLink is now updated to latest MagiBridge version.
