### ISSUE TITLE
[Request] Link channel

### ISSUE THREAD

**Issue by yepidoodles** [Eufranio/MBDiscordLink#11]
Hello,

I was wondering if we could get another channel which the bot tells us when someone has linked/ unlinked and we can check if someone has linked.

For example, when someone links or unlinks, the bot writes something like:

"DiscordUser#1234 linked with MCUsername - (UUID)"
"DiscordUser#1234 unlinked from MCUsername (UUID)"

For checking, perhaps a command such as
!linkcheck MCUsername
Which returns something like this:
"MCUsername (UUID) is linked with DiscordUser#1234"

Thanks :)

**Comment by Eufranio** [comment]
For checking if someone has linked, I've added the `/whois <player>` and `!whois @User` commands, so via the game or Discord you can check the link status of a player/user. 

For the messages on link/unlink, I've added %player% and %user% placeholders to the link/unlink commands, so you can have it to run commands like `/mb link-channel "The player %player% just linked with %user%`, and MagiBridge will send the message for you.

Those features are available in the last version of MBDiscordLink. Update MagiBridge as well.
