### ISSUE TITLE
Syncing backwards

### ISSUE THREAD

**Issue by JustIvory** [Eufranio/MBDiscordLink#5]
I want to be able to add roles to my players by assigning roles in Discord. However, it seems that it always syncs in the opposite direction and removes the Discord roles. I'd like to see a config option added to sync this way instead.

**Comment by willbattel** [comment]
+1 on this. I want to assign users to LuckPerms groups based on their Discord roles.

**Comment by mrdeadlocked** [comment]
+1 I want this also! I actually thought this was how it was supposed to work. X.X

**Comment by Eufranio** [comment]
Added on the latest version!

**Comment by willbattel** [comment]
Thanks @Eufranio really appreciate it.
