### ISSUE TITLE
getting this error very often in console

### ISSUE THREAD

**Issue by KhaozFrost** [Eufranio/MBDiscordLink#6]
22.06 02:54:01 [Server] Server thread/ERROR [Sponge]: The Scheduler tried to run the task MBDiscordLink Role Sync Task owned by Plugin{id=mbdiscordlink, name=MBDiscordLink-API7, version=1.4, description=Addon for MagiBridge that links in-game accounts with Discord accounts, authors=[Eufranio], source=./mods/MBDiscordLink-API7-1.4.jar}, but an error occured. 22.06 02:54:01 [Server] INFO java.lang.NullPointerException: null 22.06 02:54:01 [Server] INFO at com.magitechserver.mbdiscordlink.RoleSyncTask.accept(RoleSyncTask.java:39) ~[RoleSyncTask.class:?] 22.06 02:54:01 [Server] INFO at com.magitechserver.mbdiscordlink.RoleSyncTask.accept(RoleSyncTask.java:17) ~[RoleSyncTask.class:?] 22.06 02:54:01 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3148] 22.06 02:54:01 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3148] 22.06 02:54:01 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3148] 22.06 02:54:01 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3148] 22.06 02:54:01 [Server] INFO at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_151] 22.06 02:54:01 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3148] 22.06 02:54:01 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3148] 22.06 02:54:01 [Server] INFO at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2705-7.1.0-BETA-3148] 22.06 02:54:01 [Server] INFO at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:323) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3148] 22.06 02:54:01 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?] 22.06 02:54:01 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?] 22.06 02:54:01 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652) [EventBus.class:?] 22.06 02:54:01 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590) [EventBus.class:?] 22.06 02:54:01 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?] 22.06 02:54:01 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?] 22.06 02:54:01 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?] 22.06 02:54:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Eufranio** [comment]
Try with the latest version from Ore please: https://ore.spongepowered.org/Eufranio/MBDiscordLink/versions/1.5
