### ISSUE TITLE
Not syncing role.

### ISSUE THREAD

**Issue by tonnic** [Eufranio/MBDiscordLink#8]
I have this
# Interval between every role sync check, in seconds
# Set to 0 to disable. The minimum value is 15 seconds
role-sync-interval=60
# A key-value list with roles that should sync with in-game groups
# The format is "<in-game permission node>"="discord-role-id"
roles-to-sync {
    "group.mythril"="530371377480466433"

The roles are syncing with LuckPerms.

**Comment by Eufranio** [comment]
Try with the latest version.
