### ISSUE TITLE
Not showing players in topic

### ISSUE THREAD

**Issue by verpy** [Eufranio/MBDiscordLink#9]
The latest update 2.7. The topic updater for players online on the server is not working. Its stuck at zero for me

**Comment by Corcustos** [comment]
Can confirm this is also happening to me with MagiBridge. Downgrading to 2.6.2 fixed the solution with zero config changes. Wrong github though, this is for DiscordLink, which is an addon for[ MagiBridge](https://github.com/Eufranio/MagiBridge/issues).
